# Please do not directly edit this file. Instead, modify the .env variables related to NGINX configuration.

server {
    listen 443 ssl;
    server_name studio-admin.mind-verse.de;

    # SSL configuration
    ssl_certificate /etc/ssl/dify.crt;
    ssl_certificate_key /etc/ssl/dify.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # HSTS (uncomment if you're sure)
    # add_header Strict-Transport-Security "max-age=63072000" always;

    # Root directory and index files
    root /var/www/html;
    index index.html index.htm;

    # Proxy settings
    include /etc/nginx/proxy.conf;

    # API service
    location /api/ {
        proxy_pass http://docker-api-1:5001/;
    }

    # Web service
    location / {
        proxy_pass http://docker-web-1:3000/;
    }
}